# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-09 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('comentario', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PontosUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pontos', models.IntegerField()),
                ('elo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_usuario', to='main.Elo')),
            ],
        ),
    ]
