# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-11 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elo',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
