# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-11 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180110_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='elo',
            name='rank',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
