# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-11 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_elo_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosusuario',
            name='partidas_ganhas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pontosusuario',
            name='partidas_jogadas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pontosusuario',
            name='partidas_perdidas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
